import './globals.css'
import { Raleway } from 'next/font/google'

const raleway = Raleway({
    variable: '--font-raleway',
    weight: ['400', '500', '600'],
    subsets: ['latin'] 
  })

export const metadata = {
  title: 'Voting app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  )
}
